import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist, Roboto_Slab, Titan_One } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Navbar from "~/components/Navbar";

export const metadata: Metadata = {
  title: "TEDxITB 9.0",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const robotoSlab = Roboto_Slab({
  subsets: ["latin"],
  variable: "--font-roboto-slab",
});

const titanOne = Titan_One({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-titan-one",
})

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${robotoSlab.variable} ${titanOne.variable} `}>
      <body>
        <TRPCReactProvider>
            <Navbar />
           {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
